Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -11,29 +11,33 @@ jobs:
 
     strategy:
       matrix:
-        node-version: [18.x]
+        node-version: [18.x, 20.x, 22.x]
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
     - uses: actions/checkout@v4
 
-    # Set up Node.js
+    # Set up Node.js in the Backend directory
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
-        cache: 'npm'  # This caches npm dependencies but won't affect your working directory
-
-    # Install dependencies manually in the Backend folder
-    - name: Install dependencies in Backend
+        cache: 'npm'
+    
+    # Check for lock file in the Backend directory
+    - name: Check for lock file
       run: |
-        cd Backend  # Change to the Backend directory
-        npm ci  # Install dependencies in the Backend folder
-      working-directory: ./Backend  # Ensure npm ci is executed in the Backend folder
+        if [ ! -f ./Backend/package-lock.json ]; then
+          echo "Error: Dependencies lock file is not found in ./Backend."
+          exit 1
+        fi
+
+    # Install dependencies in the Backend directory
+    - name: Install dependencies
+      run: npm ci
+      working-directory: ./Backend  # Ensure you're installing dependencies from the Backend folder
 
     # Restart PM2 from the Backend directory
-    - name: Restart PM2 in Backend
-      run: |
-        cd Backend  # Change to the Backend directory
-        pm2 restart Backend  # Restart PM2 with the correct config
-      working-directory: ./Backend  # Ensure PM2 is restarted in the Backend folder
+    - name: Restart PM2
+      run: pm2 restart Backend
+      working-directory: ./Backend  # Ensure you're restarting PM2 in the Backend folder
